### ISSUE TITLE
OverlayLayer 中部分handler 的runnable 可能会报错

### ISSUE THREAD

**Issue by x930073498** [goweii/Layer#10]
![image](https://user-images.githubusercontent.com/16031755/197691295-98e67320-3e0c-4a58-8794-98b4874978b6.png)
 getViewHolder().getOverlay() 这部分可能会报错
![image](https://user-images.githubusercontent.com/16031755/197691527-c672fa76-d0bb-49aa-9400-3818f7526e70.png)

**Comment by goweii** [comment]
有没有复现路径？

**Comment by goweii** [comment]
发现问题了，周末修复。

**Comment by goweii** [comment]
更新1.0.3试下

**Comment by x930073498** [comment]
ok 辛苦啦
