### ISSUE TITLE
无法沉浸式 打开后无法超过状态栏 开启导航栏会超过导航栏显示

### ISSUE THREAD

**Issue by Xiaolangs** [goweii/Layer#13]

**Comment by goweii** [comment]
截图来一个？

**Comment by Xiaolangs** [comment]
![1679533563937](https://user-images.githubusercontent.com/26102232/227072687-405a8b1d-a958-4afc-99a0-5885a939c105.jpg)
目标效果应该是全屏  demo里也有该情况存在

**Comment by Xiaolangs** [comment]
> 截图来一个？
你好

**Comment by goweii** [comment]
dialoglayer有个setAvoidStatusBar方法，可以试下。

**Comment by Xiaolangs** [comment]
> dialoglayer有个setAvoidStatusBar方法，可以试下。

无效 默认就是false

**Comment by goweii** [comment]
等我周末看下。

**Comment by goweii** [comment]
你的activity是沉浸的吗？

**Comment by Xiaolangs** [comment]
> 你的activity是沉浸的吗？

是的 目前我是利用添加backgroundview 伪解决。因为backgroundview是全屏这样解决也只能针对纯色的页面。

**Comment by goweii** [comment]
你可以继承dialoglayer并复写fitDecorInsets方法实现自定义沉浸模式。

**Comment by Xiaolangs** [comment]
> dialoglayer

等我有时间我试试 不过这个功能希望可以你直接提供开关

**Comment by goweii** [comment]
目前对dialoglayer的定位就是避开状态栏和导航栏，为保持api尽可能精简，因此目前不考虑提供沉浸的开关。但仍可以通过继承实现自定义。

**Comment by goweii** [comment]
更新[1.0.5版本](https://github.com/goweii/Layer/releases/tag/1.0.5)
