### ISSUE TITLE
How to prevent appearing new Notification over previous Notification?

### ISSUE THREAD

**Issue by USisFounderOfISIS** [goweii/Layer#14]
How to prevent appearing new Notification over previous Notification?

1- I want behavior something like Snackbar, current Snackbar will be dismissed if new Snackbar is started. ([see this](https://raw.githubusercontent.com/danimahardhika/cafebar/master/arts/demo-0.gif) for example )

2- How to disable dismiss on swipe feature?

Thanks for this nice library.

**Comment by goweii** [comment]
你提到的这两个特性确实很普遍。最快周末发新版本支持。
你也可以参考NotificationLayer和ToastLayer自定义一个CustomLayer。

**Comment by goweii** [comment]
已支持，升级1.0.4版本
