### ISSUE TITLE
自定义键盘怎么跟edittext绑定呢？

### ISSUE THREAD

**Issue by f262866551** [goweii/Layer#18]
没看到KeyboardLayer的点击事件监听也

**Comment by goweii** [comment]
attachTextView 用于绑定textview
addActionListener 用于拦截按键事件

**Comment by f262866551** [comment]
> KeyboardLayer

有没有API限制只能显示数字键盘或者字母键盘

**Comment by goweii** [comment]
只能指定默认打开样式，不能限制只能使用某种样式。
想自定义可以使用setcontentview去自定义，保持控件id一样就行。
