### ISSUE TITLE
根布局为ConstraintLayout时DialogLayer不能横向铺满，设置match_parent也无效

### ISSUE THREAD

**Issue by Linmuge** [goweii/Layer#4]
如题

**Comment by goweii** [comment]
我用simple里面的bottom_sheet试了下，根布局修改为constraintLayout，可以横行铺满。

请fork项目新建一个复现的module，以便进一步分析，节约时间。

**Comment by Linmuge** [comment]
https://dl.muge.info/LayerDemo.zip

这是可复现的demo

**Comment by goweii** [comment]
因为你用了viewbinding，但是inflate的时候又没有传入parent，而且此时也拿不到parent，所以布局的layoutparam没有解析，所以就默认用wrapparent处理了。

可以直接传布局id进去。或者等我以后支持viewbinding，时间就不确定了。

**Comment by Linmuge** [comment]
好的，辛苦

**Comment by mark2L** [comment]
@Linmuge 
DialogInputMacBinding dialogInputMacBinding = DataBindingUtil.inflate(getLayoutInflater(), R.layout.dialog_input_arg, (ViewGroup) binding.getRoot().getParent(), false);
        dialogInputMacBinding.setInputArg(testInputArg);
        dialogInputMacBinding.setType(type);

 new DialogLayer(this)
                .setContentView(dialogInputMacBinding.getRoot())
                .setBackgroundDimDefault()
                .setGravity(Gravity.CENTER)
                .addInputMethodCompat(true)
                .addOnClickToDismissListener(R.id.fl_dialog_no)
                .show();

这样应该可以解决你的问题
