### ISSUE TITLE
Didn't find class "androidx.startup.InitializationProvider"

### ISSUE THREAD

**Issue by Liususu-cn** [goweii/Layer#5]
项目集成运行时报 Didn't find class "androidx.startup.InitializationProvider"
需要添加该库
implementation "androidx.startup:startup-runtime:x.x.x"

**Comment by goweii** [comment]
是的。
你如果引入了layer-startup模块，或者全量引入了layer项目，是需要手动引入androidx.startup依赖的。因为layer-startup模块是以compileOnly的方式引入的androidx.startup。

**Comment by goweii** [comment]
是的。
你如果引入了layer-startup模块，或者全量引入了layer项目，是需要手动引入androidx.startup依赖的。因为layer-startup模块是以compileOnly的方式引入的androidx.startup。
