### ISSUE TITLE
Layer 能层叠？如 DialogLayer 展示后再展示 PopupLayer。

### ISSUE THREAD

**Issue by AversonCoder** [goweii/Layer#6]
如题，感谢。

**Comment by goweii** [comment]
可以的，layer有层级关系，层级参考[FrameLayer](https://github.com/goweii/Layer/blob/master/layer-core/src/main/java/per/goweii/layer/core/FrameLayer.java)内部定义的Level

**Comment by AversonCoder** [comment]
已解决，非常感谢。
