### ISSUE TITLE
guideLayer 在部分机型中，熄屏后重新点亮会出现guideLayer位置不准的情况

### ISSUE THREAD

**Issue by x930073498** [goweii/Layer#7]

**Comment by x930073498** [comment]
![image](https://user-images.githubusercontent.com/16031755/191482310-527d04e6-58b4-4987-a81d-ebc315a68583.png)
如图

**Comment by Xiaolangs** [comment]
这个问题有办法解决吗

**Comment by goweii** [comment]
抓下灭屏前和亮屏后的界面布局，把布局边界打开。对比下是哪里导致的。

目前没时间处理这个bug，你可以先自己分析一下。

或者你可以尝试再亮屏后延迟会调用下updateLocation试下。

**Comment by Xiaolangs** [comment]
> 抓下灭屏前和亮屏后的界面布局，把布局边界打开。对比下是哪里导致的。
> 
> 目前没时间处理这个bug，你可以先自己分析一下。
> 
> 或者你可以尝试再亮屏后延迟会调用下updateLocation试下。

好的好的

**Comment by Xiaolangs** [comment]
> 抓下灭屏前和亮屏后的界面布局，把布局边界打开。对比下是哪里导致的。
> 
> 目前没时间处理这个bug，你可以先自己分析一下。
> 
> 或者你可以尝试再亮屏后延迟会调用下updateLocation试下。

  方便加您一个联系方式吗

**Comment by goweii** [comment]
bug在issue讨论，可以方便跟踪问题。

技术交流可以加QQ群147715512

**Comment by goweii** [comment]
自测设备有限，使用demo尝试了很多次都没有复现到这个现象。
如果可以，希望可以尝试分析下，提供下问题原因或直接提PR修复。
感谢。

**Comment by AweiLoveAndroid** [comment]
看截图，y轴偏移量刚好是是状态栏的高度。设置位置的时候，是否要排除一下状态栏高度？

**Comment by goweii** [comment]
这个高度看起来不是状态栏的高度，偏移的距离比状态栏小点。
@AweiLoveAndroid 可以试下继承GuideLayer，复写fitDecorInsets方法并注释掉super.fitDecorInsets的调用来让页面全屏，看是是否可以完全规避这个问题。
