### ISSUE TITLE
Layer 如何在保持状态的情况下，隐藏？

### ISSUE THREAD

**Issue by lcyluo** [goweii/Layer#8]
目前使用Layer框架，解决了我很多类似弹窗，PopWindow之类的问题.

在使用过程中，假设弹窗页面比较复杂，里面内容有类似选中，类似填写内容等情况，
有多次调用显示隐藏，原有的状态无法保存，会出现页面数据归零的情况。

不知道是否有单纯只隐藏显示，但是实际弹窗并未销毁的功能；

**Comment by goweii** [comment]
有一个 setViewCacheable 方法，设置为 true 可以缓存视图，show 和 dismiss 照常调用即可。
